version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: next_app
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - CONVEX_DEPLOYMENT="${CONVEX_DEPLOYMENT:-default}"
    expose:
      - "3000"
    networks:
      - battleworld

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html/public
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - battleworld

  trivy:
    image: aquasec/trivy:latest
    container_name: trivy_scan
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["trivy", "image", "--exit-code", "0", "next_app"]

networks:
  battleworld:
    driver: bridge